name: earthml
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ==3.8.8
  - cartopy
  - colorcet
  - dask
  - dask-ml
  - pillow
  - piexif
  - exifread
  - descartes
  - pysal
  - seaborn
  - plotly
  - opencv
  - geopandas
  - graphviz
  - numpy
  - pandas
  - panel ==0.4.0
  - python-graphviz
  - rasterio
  - s3fs
  - scikit-image
  - scikit-learn
  - tqdm
  - imgaug
  - joblib
  - keras==2.2.4
  - h5py==2.10.0
  - defaults::scipy
  - pip:
    - rio-toa
    - nc-time-axis
    - netCDF4
